language: node_js
node_js:
  - '6.4.0'
notifications:
  email: false
before_install:
  - travis_retry nvm install 6.4.0
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
      npm install request;
      npm run update-package;
    fi
env:
  global:
    - secure: "CcU24T71/rGvU+CxBaZ+9TlkI6USSjPfZ29RF7Rc0T7squ9t6jUdZl+a4DVizr68EtyDkGReSZq8aAJtr+Nbk/6nCZnyIPA/Iib34FtzOPT0fDjRYyM3qKXHTPxmXrevASniKBTEddF0FVnqU0+vSh9ryNTRQvbTsA1/izdsOYQ="
    - MERGE_TOKEN=fcf6b3ed1d9fb0b88316cd7e66ccafd4f6cb83fe
    - SENDGRID_USERNAME=azai91
    - secure: "dbp9zLsc/R3KV2szdeGVUlbnMlo02QeCQ3hdO8861/LENe1BO/P04WPDM0Sto5pA28SMfI9uSLyeOwyS40r6zFtV1gjgW9iXjQOlAhtmO0TZ29n1sPQdNvhJNkq2QB5ipZhhZp0PBMaKR8PZRORZGKnZRvZ2kjs77AxR5s9fuJw="
    - secure: "IefyZiRK6R6a1RuMVRj1y9APRqivqR8uZ8sbsgYfPe3R2kKqN/Riu+hMG/c4P1ZIrvpd/6EYimdwsn+E4ex6YLe+Bhx3/igw9x/WEqZ56N61zWgTt8G7B6HtVs2yfBgiyhXY9sNJwgy0xePQDfH4REfkmeVL+bslg9pNtIITqrU="
    - secure: "ERN4GUhV/WtPHOhB1HzAIw+G0xow9vAWwx8HpdD2kUjGl7QoNtVk6Duys7txq0EiBIY4vDZBfvU+yVpUyswJvEaw/5q+dZ+4Py311uebjbqHSdQNiY9hHCqJ2TGng0uVWz+2tzV5CJQ7e+jXaHwcUBv38ha74hO9y6nuh2hixeI="
script:
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then
      npm run get-test-utils && npm run test ; npm run lint ; npm run report;
    else
      npm run merge;
    fi
