// DO NOT EDIT THIS FILE
let messageArr = require('./mockDB');

module.exports = {
  create: (msgObj, callback) => {

    if (!msgObj.created_by || !msgObj.message) {
      return callback('Invalid message object');
    }

    messageArr.push({
      created_by: msgObj.created_by,
      created_at: Date.now(),
      message: msgObj.message,
    });

    return callback(null);
  },

  find: (criteria, callback) => {
    const foundMessages = messageArr.filter((msg) => {

      for (let key in criteria) {
        if (!msg.hasOwnProperty(key)) return callback(true, null);
      }
      return true;
    });

    return callback(null, foundMessages);
  },

  remove: (criteria, callback) => {
    const msgsToKeep = messageArr.filter((msg) => {

      for (let key in criteria) {
        if (!msg.hasOwnProperty(key) || msg[key] !== criteria[key]) return false;
      }
      return true;
    });

    messageArr = msgsToKeep;
    return callback(null, true);
  }
}
